export const tokens = {
  color: {
    night: { '900': '#0A1017', '800': '#121A24', '700': '#1C2632' },
    slate: {
      '100': '#F1F5F9',
      '200': '#E2E8F0',
      '300': '#FFFFFF',
      '400': '#94A3B8',
      '500': '#64748B',
      '600': '#1E293B',
      '700': '#475569',
      '900': '#0F172A',
    },
    white: '#F8FAFC',
    primary: '#0F766E',
    'primary-hover': '#0D5E57',
    accent: '#14B8A6',
    'accent-hover': '#0D9488',
    highlight: '#22D3EE',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#DC2626',
    'error-hover': '#B91C1C',
    info: '#3B82F6',
  },
  font: {
    heading: "'Space Grotesk', sans-serif",
    body: "'Inter', sans-serif",
    mono: "'JetBrains Mono', monospace",
  },
  text: {
    display: { size: '72px', lineHeight: 1.0, weight: 700 },
    h1: { size: '56px', lineHeight: 1.05, weight: 700 },
    h2: { size: '44px', lineHeight: 1.1, weight: 600 },
    h3: { size: '32px', lineHeight: 1.15, weight: 600 },
    h4: { size: '24px', lineHeight: 1.2, weight: 600 },
    h5: { size: '18px', lineHeight: 1.3, weight: 600 },
    h6: { size: '16px', lineHeight: 1.4, weight: 600 },
    body: { size: '15px', lineHeight: 1.6, weight: 400 },
    'body-sm': { size: '14px', lineHeight: 1.5, weight: 400 },
    caption: { size: '13px', lineHeight: 1.4, weight: 500 },
    tiny: { size: '12px', lineHeight: 1.3, weight: 500 },
  },
  space: {
    2: '8px', 4: '16px', 6: '24px', 8: '32px',
    12: '48px', 16: '64px', 20: '80px', 24: '96px',
  },
  radius: {
    sm: '6px',
    lg: '12px',
  },
  duration: {
    fast: '100ms',
    base: '200ms',
    slow: '300ms',
  },
  ease: {
    out: [0.16, 1, 0.3, 1],
    'in-out': [0.4, 0, 0.2, 1],
    linear: [0, 0, 1, 1],
  },
  z: {
    base: 0,
    sticky: 10,
    dropdown: 20,
    sidebar: 30,
    'modal-bg': 40,
    modal: 50,
    toast: 60,
  },
  elevation: {
    0: { shadow: 'none' },
    1: { shadow: '0 1px 3px rgba(0,0,0,0.25)', 'shadow-light': '0 1px 3px rgba(0,0,0,0.06)' },
    2: { shadow: '0 4px 12px rgba(0,0,0,0.3)', 'shadow-light': '0 4px 12px rgba(0,0,0,0.08)' },
    3: { shadow: '0 4px 12px rgba(0,0,0,0.3)', 'shadow-light': '0 4px 12px rgba(0,0,0,0.08)' },
    4: { shadow: '0 8px 32px rgba(0,0,0,0.4)', 'shadow-light': '0 8px 32px rgba(0,0,0,0.1)' },
    5: { shadow: '0 8px 32px rgba(0,0,0,0.4)', 'shadow-light': '0 8px 32px rgba(0,0,0,0.1)' },
  },
  density: {
    comfort: { paddingCard: '24px', gapGrid: '24px', inputHeight: '44px', rowHeight: '56px' },
    balanced: { paddingCard: '20px', gapGrid: '20px', inputHeight: '40px', rowHeight: '48px' },
    compact: { paddingCard: '16px', gapGrid: '16px', inputHeight: '36px', rowHeight: '40px' },
  },
  semantic: {
    surface: {
      primary: 'var(--surface-primary)',
      secondary: 'var(--surface-secondary)',
      tertiary: 'var(--surface-tertiary)',
      elevated: 'var(--surface-elevated)',
    },
    text: {
      primary: 'var(--text-primary)',
      secondary: 'var(--text-secondary)',
      tertiary: 'var(--text-tertiary)',
      inverse: 'var(--text-inverse)',
    },
    border: {
      default: 'var(--border-default)',
      subtle: 'var(--border-subtle)',
      accent: 'var(--border-accent)',
    },
    interactive: {
      primary: 'var(--interactive-primary)',
      'primary-hover': 'var(--interactive-primary-hover)',
      accent: 'var(--interactive-accent)',
      'accent-hover': 'var(--interactive-accent-hover)',
      focus: 'var(--interactive-focus)',
      disabled: 'var(--interactive-disabled)',
    },
    status: {
      success: 'var(--status-success)',
      'success-bg': 'var(--status-success-bg)',
      warning: 'var(--status-warning)',
      'warning-bg': 'var(--status-warning-bg)',
      error: 'var(--status-error)',
      'error-bg': 'var(--status-error-bg)',
      'error-hover': 'var(--status-error-hover)',
      info: 'var(--status-info)',
      'info-bg': 'var(--status-info-bg)',
    },
  },
} as const;

export type Tokens = typeof tokens;